// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyznkpmoflmgkfofpcsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5em5rcG1vZmxtZ2tmb2ZwY3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTA4NTUsImV4cCI6MjA2NTU4Njg1NX0.epAbbIWgjF3icWGXpkZV_5lAzPKo8UMeT55yB2nfNE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);